language: cpp
sudo: required
compiler:
  - gcc
  - clang

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - if [ $TRAVIS_BRANCH = "master" ]; then sudo apt-get -qq install doxygen; fi

install:
  # Pull Docker image
  - docker pull tatsy/ubuntu-cxx:opencv

  # Dynamically generate Dockerfile
  - sed -i -e "s/@C_COMPILER@/$CC/;s/@CXX_COMPILER@/$CXX/;s/@BRANCH_NAME@/$TRAVIS_BRANCH/;s/@PULL_REQUEST@/$TRAVIS_PULL_REQUEST/" Dockerfile

  # Build Dockerfile
  - docker build --tag=lime-env .

  # Run container
  - docker run --name lime-env --env="CI=true" --env="TRAVIS_JOB_ID=$TRAVIS_JOB_ID" --env="CTEST_OUTPUT_ON_FAILURE=TRUE" -itd lime-env

script:
  # Run test on Docker container
  - docker exec lime-env make check

after_success:
  # Collect coverage
  - if [ $CXX = "g++"     ]; then docker exec lime-env lcov --directory . --capture --output-file coverage.info; fi
  - if [ $CXX = "clang++" ]; then docker exec lime-env lcov --directory . --capture --output-file coverage.info --gcov-tool llvm-cov-3.5; fi
  - docker exec lime-env lcov --remove coverage.info 'tests/*' 'examples/*' '/usr/*' 'CMakeFiles/*' --output-file coverage.info
  - docker exec lime-env lcov --list coverage.info
  - docker exec lime-env coveralls-lcov --repo-token c6Fd5h2Ovd2c5PV7agagA89sUhsZCwIPR coverage.info

before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - "cd docs; doxygen doxyfile; cd -"
  - mkdir packages
  - tar czvf packages/releases-$GIT_TAG.tar.gz $(ls -I packages)
  - zip -q packages/releases-$GIT_TAG.zip -r $(ls -I packages)
  - git tag $GIT_TAG -a -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GH_TOKEN@github.com/lime.git --tags 2> /dev/null

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kEV14WgxyZwIrd/tKScLKCk9vSSkqSZIvmfcSwvLrxKWYU6t5wmXkoIwfq1TMWWOGd9pSAAWtx7w2ofdA7OUXJyfW2I/azug1J+3zhzChbeVLNbt69orHZNbTbOddcTLKMUI43cEPk5Qn3cVxoRAwN1zF/s8VGiBE4zQaLSz6Ck=
  file:
    - packages/releases-$GIT_TAG.tar.gz
    - packages/releases-$GIT_TAG.zip
  on:
    tags: false
    branch: master
    condition: $CXX=clang++

branches:
  only:
    - master
    - development

env:
  global:
    - GIT_TAG=v0.1.0
    - secure: kEV14WgxyZwIrd/tKScLKCk9vSSkqSZIvmfcSwvLrxKWYU6t5wmXkoIwfq1TMWWOGd9pSAAWtx7w2ofdA7OUXJyfW2I/azug1J+3zhzChbeVLNbt69orHZNbTbOddcTLKMUI43cEPk5Qn3cVxoRAwN1zF/s8VGiBE4zQaLSz6Ck=

notifications:
    email:
        recipients: tatsy.mail@gmail.com
        on_success: change
        on_failure: always
