language: cpp

compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get -y install libopencv-dev build-essential cmake git libgtk2.0-dev pkg-config python-dev python-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libpng12-dev libtiff4-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libxine-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libv4l-dev libtbb-dev libqt4-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip
    - mkdir opencv
    - cd opencv
    - wget https://github.com/Itseez/opencv/archive/3.0.0-beta.zip
    - unzip 3.0.0-beta.zip
    - cd opencv-3.0.0-beta
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
    - make
    - sudo make install
    - sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
    - sudo ldconfig
    - cd ../../..
    - sudo pip install cpp-coveralls

install:
    - sudo apt-get install libgtest-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libgtest* /usr/local/lib ; cd -"
    - export GTEST_LIBRARY=/usr/local/lib/libgtest.a
    - export GTEST_MAIN_LIBRARY=/usr/local/lib/libgtest_main.a
    - export GTEST_INCLUDE_DIRS=/usr/include
    - mkdir build
    - cd build
    - cmake ..

script:
    - make && make test

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '-\lp'

notifications:
    email:
        recipients: tatsy.mail@gmail.com
        on_success: change
        on_failure: always
